--------------------------------------------------------------------------------
-- OpsFlow - Script de creación del esquema (DDL)
-- Motor: Oracle Database (compatible con apex.oracle.com / Oracle 19c+)
--
-- Convenciones:
--   * Prefijo OPS_ para todas las tablas del proyecto.
--   * PK con IDENTITY (auto-incremental nativo de Oracle 12c+).
--     -> Equivale al "Id" autogenerado que te da Dataverse en Power Apps.
--   * CHAR(1) 'S'/'N' para flags booleanos (patrón habitual en Oracle).
--
-- Idempotente: podés re-ejecutar el script; primero elimina los objetos si existen.
--------------------------------------------------------------------------------

-- Limpieza previa (ignora el error si el objeto no existe todavía).
BEGIN
  FOR t IN (SELECT table_name
              FROM user_tables
             WHERE table_name IN ('OPS_TICKET_HISTORIAL','OPS_TICKET',
                                  'OPS_AGENTE','OPS_PRIORIDAD','OPS_CATEGORIA'))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

--------------------------------------------------------------------------------
-- Tabla: OPS_CATEGORIA
--------------------------------------------------------------------------------
CREATE TABLE ops_categoria (
  id_categoria  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre        VARCHAR2(60)  NOT NULL,
  descripcion   VARCHAR2(200),
  activo        CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_ops_categoria PRIMARY KEY (id_categoria),
  CONSTRAINT ck_categoria_activo CHECK (activo IN ('S','N')),
  CONSTRAINT uk_categoria_nombre UNIQUE (nombre)
);

--------------------------------------------------------------------------------
-- Tabla: OPS_PRIORIDAD  (sla_horas define el acuerdo de nivel de servicio)
--------------------------------------------------------------------------------
CREATE TABLE ops_prioridad (
  id_prioridad  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre        VARCHAR2(30) NOT NULL,
  sla_horas     NUMBER       NOT NULL,
  activo        CHAR(1)      DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_ops_prioridad PRIMARY KEY (id_prioridad),
  CONSTRAINT ck_prioridad_activo CHECK (activo IN ('S','N')),
  CONSTRAINT ck_prioridad_sla CHECK (sla_horas > 0),
  CONSTRAINT uk_prioridad_nombre UNIQUE (nombre)
);

--------------------------------------------------------------------------------
-- Tabla: OPS_AGENTE
--------------------------------------------------------------------------------
CREATE TABLE ops_agente (
  id_agente  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre     VARCHAR2(100) NOT NULL,
  email      VARCHAR2(120) NOT NULL,
  activo     CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_ops_agente PRIMARY KEY (id_agente),
  CONSTRAINT ck_agente_activo CHECK (activo IN ('S','N')),
  CONSTRAINT uk_agente_email UNIQUE (email)
);

--------------------------------------------------------------------------------
-- Tabla: OPS_TICKET  (entidad central)
--------------------------------------------------------------------------------
CREATE TABLE ops_ticket (
  id_ticket         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_categoria      NUMBER        NOT NULL,
  id_prioridad      NUMBER        NOT NULL,
  id_agente         NUMBER,
  titulo            VARCHAR2(150) NOT NULL,
  descripcion       VARCHAR2(2000),
  estado            VARCHAR2(20)  DEFAULT 'NUEVO' NOT NULL,
  fecha_creacion    DATE          DEFAULT SYSDATE NOT NULL,
  fecha_limite      DATE,
  fecha_resolucion  DATE,
  cumplio_sla       CHAR(1),
  CONSTRAINT pk_ops_ticket PRIMARY KEY (id_ticket),
  CONSTRAINT fk_ticket_categoria FOREIGN KEY (id_categoria) REFERENCES ops_categoria (id_categoria),
  CONSTRAINT fk_ticket_prioridad FOREIGN KEY (id_prioridad) REFERENCES ops_prioridad (id_prioridad),
  CONSTRAINT fk_ticket_agente    FOREIGN KEY (id_agente)    REFERENCES ops_agente (id_agente),
  CONSTRAINT ck_ticket_estado    CHECK (estado IN ('NUEVO','EN_PROCESO','RESUELTO','CERRADO')),
  CONSTRAINT ck_ticket_sla       CHECK (cumplio_sla IN ('S','N'))
);

--------------------------------------------------------------------------------
-- Tabla: OPS_TICKET_HISTORIAL  (auditoría de transiciones de estado)
--------------------------------------------------------------------------------
CREATE TABLE ops_ticket_historial (
  id_historial     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_ticket        NUMBER        NOT NULL,
  estado_anterior  VARCHAR2(20),
  estado_nuevo     VARCHAR2(20)  NOT NULL,
  usuario          VARCHAR2(60)  DEFAULT USER NOT NULL,
  fecha_cambio     DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_ops_historial PRIMARY KEY (id_historial),
  CONSTRAINT fk_historial_ticket FOREIGN KEY (id_ticket) REFERENCES ops_ticket (id_ticket)
);

--------------------------------------------------------------------------------
-- Índices para acelerar los filtros del dashboard / reportes
--------------------------------------------------------------------------------
CREATE INDEX ix_ticket_estado    ON ops_ticket (estado);
CREATE INDEX ix_ticket_prioridad ON ops_ticket (id_prioridad);
CREATE INDEX ix_ticket_agente    ON ops_ticket (id_agente);
CREATE INDEX ix_historial_ticket ON ops_ticket_historial (id_ticket);

--------------------------------------------------------------------------------
-- Comentarios de tabla/columna (documentación viva dentro de la base)
--------------------------------------------------------------------------------
COMMENT ON TABLE  ops_ticket              IS 'Solicitudes operativas gestionadas por OpsFlow.';
COMMENT ON COLUMN ops_ticket.fecha_limite IS 'Fecha límite calculada: creación + SLA de la prioridad.';
COMMENT ON COLUMN ops_ticket.cumplio_sla  IS 'S/N. Se calcula al resolver el ticket.';
COMMENT ON TABLE  ops_ticket_historial    IS 'Auditoría de cambios de estado por ticket.';

PROMPT ============================================================
PROMPT  OpsFlow: esquema creado correctamente.
PROMPT  Siguiente paso: ejecutar 02_logic/01_pkg_ops_ticket.sql
PROMPT ============================================================
